version: "3.1"
services:
  # Replica Set (required for Prisma Client)
  mongo:
    build: ./mongodb_rs
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'

  node:
    image: "soph-notes"
    build:
      context: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    command: "npm run dev"
